rm(list=ls())
library(MASS)
library(ggplot2)
library(grid)
library (gridExtra)
library(npmlreg)

T=nrep=100
beta=c(0.2,0.2)
p=length(beta)
a1=-1
a2=1
results=matrix(0,44,9)
#############################poisson model with m=50#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=NULL
for(i in 1:nrep){
  res= paste('Results/poisson-50/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[1,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[2,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[3,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[4,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[5,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################poisson model with m=100#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=NULL
for(i in 1:nrep){
  res= paste('Results/poisson-100/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[6,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[7,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[8,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[9,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[10,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################logistic model with m=50#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=NULL
for(i in 1:nrep){
  res= paste('Results/logistic-50/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[11,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[12,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[13,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[14,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[15,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################logistic model with m=100#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=NULL
for(i in 1:nrep){
  res= paste('Results/logistic-100/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[16,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[17,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[18,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[19,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[20,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################overdispersed poisson model with m=50#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=aMSE_rqs=aMSE_fqs=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=betarqs=se.beta_rqs=betafqs=se.beta_fqs=NULL
for(i in 1:nrep){
  res= paste('Results/nbinom-50/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_rqs=c(aMSE_rqs,save_res$aMSE_rqs)
  aMSE_fqs=c(aMSE_fqs,save_res$aMSE_fqs)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
  betarqs=rbind(betarqs,save_res$betarqs)
  se.beta_rqs=rbind(se.beta_rqs,save_res$se.beta_rqs)
  betafqs=rbind(betafqs,save_res$betafqs)
  se.beta_fqs=rbind(se.beta_fqs,save_res$se.beta_fqs)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)
cp.beta_rqs=ifelse(abs(betarqs-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_rqs,1,0)
cp.beta_fqs=ifelse(abs(betafqs-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fqs,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
####################RE quasi#############3
aMSEmean_rqs=mean(aMSE_rqs)
betamean_rqs=apply(betarqs,2,mean)
betabias_rqs=abs(betamean_rqs-beta)
betasd_rqs=apply(betarqs,2,sd)
betase_rqs=apply(se.beta_rqs,2,mean)
betacp_rqs=apply(cp.beta_rqs,2,mean)
###############fixed effects model##################################3
aMSEmean_fqs=mean(aMSE_fqs)
betamean_fqs=apply(betafqs,2,mean)
betabias_fqs=abs(betamean_fqs-beta)
betasd_fqs=apply(betafqs,2,sd)
betase_fqs=apply(se.beta_fqs,2,mean)
betacp_fqs=apply(cp.beta_fqs,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[21,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[22,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[23,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[24,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[25,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fqs,betabias_fqs,betasd_fqs,betase_fqs,betacp_fqs)
results[26,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_rqs,betabias_rqs,betasd_rqs,betase_rqs,betacp_rqs)
results[27,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################overdispersed poisson model with m=100#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=aMSE_rqs=aMSE_fqs=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=betarqs=se.beta_rqs=betafqs=se.beta_fqs=NULL
for(i in 1:nrep){
  res= paste('Results/nbinom-100/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_rqs=c(aMSE_rqs,save_res$aMSE_rqs)
  aMSE_fqs=c(aMSE_fqs,save_res$aMSE_fqs)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
  betarqs=rbind(betarqs,save_res$betarqs)
  se.beta_rqs=rbind(se.beta_rqs,save_res$se.beta_rqs)
  betafqs=rbind(betafqs,save_res$betafqs)
  se.beta_fqs=rbind(se.beta_fqs,save_res$se.beta_fqs)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)
cp.beta_rqs=ifelse(abs(betarqs-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_rqs,1,0)
cp.beta_fqs=ifelse(abs(betafqs-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fqs,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
####################RE quasi#############3
aMSEmean_rqs=mean(aMSE_rqs)
betamean_rqs=apply(betarqs,2,mean)
betabias_rqs=abs(betamean_rqs-beta)
betasd_rqs=apply(betarqs,2,sd)
betase_rqs=apply(se.beta_rqs,2,mean)
betacp_rqs=apply(cp.beta_rqs,2,mean)
###############fixed effects model##################################3
aMSEmean_fqs=mean(aMSE_fqs)
betamean_fqs=apply(betafqs,2,mean)
betabias_fqs=abs(betamean_fqs-beta)
betasd_fqs=apply(betafqs,2,sd)
betase_fqs=apply(se.beta_fqs,2,mean)
betacp_fqs=apply(cp.beta_fqs,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[28,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[29,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[30,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[31,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[32,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fqs,betabias_fqs,betasd_fqs,betase_fqs,betacp_fqs)
results[33,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_rqs,betabias_rqs,betasd_rqs,betase_rqs,betacp_rqs)
results[34,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################5 groups with m=50#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=NULL
for(i in 1:nrep){
  res= paste('Results/5groups-50/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[35,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[36,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[37,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[38,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[39,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
#############################5 groups with m=100#####################################
aMSE=aMSE_or=aMSE_fix=aMSE_ran=aMSE_np=NULL
betaest=se.beta=betaran=se.beta_ran=betafix=se.beta_fix=betaor=se.beta_or=betanp=se.beta_np=NULL
for(i in 1:nrep){
  res= paste('Results/5groups-100/intermediate_results',i,'.Rdata',sep="")
  load(res)
  aMSE=c(aMSE,save_res$aMSE)
  aMSE_ran=c(aMSE_ran,save_res$aMSE_ran)
  aMSE_fix=c(aMSE_fix,save_res$aMSE_fix)
  aMSE_np=c(aMSE_np,save_res$aMSE_np)
  aMSE_or=c(aMSE_or,save_res$aMSE_or)
  betaest=rbind(betaest,save_res$betaest)
  se.beta=rbind(se.beta,save_res$se.beta)
  betaran=rbind(betaran,save_res$betaran)
  se.beta_ran=rbind(se.beta_ran,save_res$se.beta_ran)
  betafix=rbind(betafix,save_res$betafix)
  se.beta_fix=rbind(se.beta_fix,save_res$se.beta_fix)
  betaor=rbind(betaor,save_res$betaor)
  se.beta_or=rbind(se.beta_or,save_res$se.beta_or)
  betanp=rbind(betanp,save_res$betanp)
  se.beta_np=rbind(se.beta_np,save_res$se.beta_np)
}

#SCAD
cp.beta=ifelse(abs(betaest-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta,1,0)
cp.beta_or=ifelse(abs(betaor-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_or,1,0)
cp.beta_np=ifelse(abs(betanp-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_np,1,0)
cp.beta_ran=ifelse(abs(betaran-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_ran,1,0)
cp.beta_fix=ifelse(abs(betafix-matrix(rep(beta,nrep),ncol=2,byrow = TRUE))<1.96*se.beta_fix,1,0)

betamean=apply(betaest,2,mean)
betabias=abs(betamean-beta)
betasd=apply(betaest,2,sd)
betase=apply(se.beta,2,mean)
betacp=apply(cp.beta,2,mean)
aMSEmean=mean(aMSE)
####################random effects model#############3
aMSEmean_ran=mean(aMSE_ran)
betamean_ran=apply(betaran,2,mean)
betabias_ran=abs(betamean_ran-beta)
betasd_ran=apply(betaran,2,sd)
betase_ran=apply(se.beta_ran,2,mean)
betacp_ran=apply(cp.beta_ran,2,mean)
###############fixed effects model##################################3
aMSEmean_fix=mean(aMSE_fix)
betamean_fix=apply(betafix,2,mean)
betabias_fix=abs(betamean_fix-beta)
betasd_fix=apply(betafix,2,sd)
betase_fix=apply(se.beta_fix,2,mean)
betacp_fix=apply(cp.beta_fix,2,mean)
#######latent class#######
aMSEmean_np=mean(aMSE_np)
betamean_np=apply(betanp,2,mean)
betabias_np=abs(betamean_np-beta)
betasd_np=apply(betanp,2,sd)
betase_np=apply(se.beta_np,2,mean)
betacp_np=apply(cp.beta_np,2,mean)
###############oracle######################
aMSEmean_or=mean(aMSE_or)
betamean_or=apply(betaor,2,mean)
betabias_or=abs(betamean_or-beta)
betasd_or=apply(betaor,2,sd)
betase_or=apply(se.beta_or,2,mean)
betacp_or=apply(cp.beta_or,2,mean)

results[40,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean,betabias,betasd,betase,betacp)
results[41,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_fix,betabias_fix,betasd_fix,betase_fix,betacp_fix)
results[42,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_ran,betabias_ran,betasd_ran,betase_ran,betacp_ran)
results[43,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_or,betabias_or,betasd_or,betase_or,betacp_or)
results[44,c(1,2,6,3,7,4,8,5,9)]=c(aMSEmean_np,betabias_np,betasd_np,betase_np,betacp_np)
Model = c(rep("Poisson with 3 groups", 10), rep("Logistic with 3 groups", 10), 
          rep("Overdispersed Poisson with 3 groups", 14),rep("Poisson with 5 groups", 10))
sample_size=c(rep(c(50,100),each=5),rep(c(50,100),each=5),rep(c(50,100),each=7),rep(c(50,100),each=5))
Method = c(rep(c("SCAD", "FE","RE","Oracle", "LC"), 4),rep(c("SCAD", "Oracle","FE","RE","FE.quasi","RE.quasi","LC"),2),
           rep(c("SCAD", "FE","RE","Oracle", "LC"), 2))
colnames(results) <- c("MSE","Bias1", "SD1", "SE1", "CP1","Bias2", "SD2", "SE2", "CP2")
Table3 <- data.frame(Model=Model,sample_size,Method=Method,results)
sink("Results/Table3.csv",append=FALSE,split=TRUE)
cat("\n### Table 3 in Simulation Results ###\n")
print(Table3)
sink()
